version: "2"
services:
  onos:
    container_name: onos
    image: onosproject/onos:1.5
    networks:
      management:
        ipv4_address: 10.28.34.2
    volumes:
      - ./volumes/onos:/root/onos/config
    ports:
      - "8181:8181"
      - "8101:8101"
    environment:
      - ONOS_APPS=drivers,openflow-base,netcfghostprovider,lldpprovider,proxyarp

  mininet:
    container_name: mininet
    privileged: true
    image: iwaseyusuke/mininet
    networks:
      management:
        ipv4_address: 10.28.34.3
    volumes:
      - ./volumes/mininet:/root/script
    stdin_open: true
    tty: true
    environment:
      - DISPLAY

  app:
    container_name: app
    hostname: "louis"
    privileged: true
    image: louisnguyen96/vm-app
    networks:
      management:
        ipv4_address: 10.28.34.4
    ports:
      - "9200:9200"
      - "9300:9300"
      - "5601:5601"
      - "18630:18630"
      - "8080:8080"
    volumes:
      - ./volumes/kibana/data:/kibana/data/
      - ./volumes/logstash/data:/logstash/data/
      - ./volumes/logstash/logs:/logstash/logs/
      - ./volumes/elasticsearch/data:/elasticsearch/data/
      - ./volumes/elasticsearch/logs:/elasticsearch/logs/
      - ./volumes/streamsets/log:/streamsets/log/
      - ./volumes/streamsets/data:/streamsets/data/
    stdin_open: true
    tty: true

networks:
  management:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.28.34.0/24
          gateway: 10.28.34.1
